# 公司内网屏蔽的域名和服务
# NAME: TangXun
# AUTHOR: mr-mihu
# REPO: https://github.com/mr-mihu/clash-rules/tree/firm
# UPDATED: 2024-11-15 18:30:29
# DOMAIN-SUFFIX: 46
# PROCESS-NAME: 4
# TOTAL: 49
payload:
    # 酷狗
    - 'PROCESS-NAME,kugou.exe'
    - 'DOMAIN-SUFFIX,kugou.com'
    - 'DOMAIN-SUFFIX,tencentmusic.com'
    # 有道翻译
    - 'PROCESS-NAME,YoudaoDict'
    - 'PROCESS-NAME,YoudaoDict.exe'
    - 'PROCESS-NAME,YoudaoDictHelper.exe'
    - 'DOMAIN-SUFFIX,youdao.com'
    # 网易云音乐
    - 'DOMAIN-SUFFIX,music.163.com'
    - 'DOMAIN-SUFFIX,music.126.net'
    # 喜马拉雅
    - 'DOMAIN-SUFFIX,ximalaya.com'
    # 钉钉
    - 'DOMAIN-SUFFIX,dingtalk.com'
   #'DOMAIN-SUFFIX,down-cdn.dingtalk.com' 文件下载可以直接访问
    - 'DOMAIN-SUFFIX,dingtalkapps.com' #工作台
    - 'DOMAIN-SUFFIX,mmstat.com' #网站统计和数据分析
    - 'DOMAIN-SUFFIX,aliyuncs.com' #在线文档
   # 微信
    - 'DOMAIN-SUFFIX,wx.qlogo.cn' #头像高清图
    - 'DOMAIN-SUFFIX,wxapp.tc.qq.com' #头像缩略图
    - 'DOMAIN-SUFFIX,sticker.weixin.qq.com' #微信表情
    - 'DOMAIN-SUFFIX,channels.weixin.qq.com' #视频号 dns
    - 'DOMAIN-SUFFIX,channels.video.qq.com'
    # 英雄联盟手游
    - 'DOMAIN-SUFFIX,lolm.qq.com'
    # 抖音
    - 'DOMAIN-SUFFIX,ixigua.com' # 西瓜视频
    - 'DOMAIN-SUFFIX,ixiguavideo.com'
    - 'DOMAIN-SUFFIX,toutiao.com' # 头条
    - 'DOMAIN-SUFFIX,zijieapi.com'
    - 'DOMAIN-SUFFIX,zijiecdn.com'
    - 'DOMAIN-SUFFIX,bytetos.com'
    - 'DOMAIN-SUFFIX,bytegecko.com'
    - 'DOMAIN-SUFFIX,byteimg.com'
    - 'DOMAIN-SUFFIX,bytemastatic.com'
    - 'DOMAIN-SUFFIX,byteeffecttos.com'
    - 'DOMAIN-SUFFIX,bytescm.com' #关注视频列表
    - 'DOMAIN-SUFFIX,bytefcdnrd.com' #web 直播
    - 'DOMAIN-SUFFIX,bytedance.com'
    - 'DOMAIN-SUFFIX,ibytedtos.com'
    - 'DOMAIN-SUFFIX,douyin.com' #官网
    - 'DOMAIN-SUFFIX,douyinpic.com' #封面、弹幕、评论、点赞、礼物
    - 'DOMAIN-SUFFIX,douyinvod.com' #web 视频流
    - 'DOMAIN-SUFFIX,douyincdn.com'
    - 'DOMAIN-SUFFIX,douyinstatic.com' #web 二维码登录弹窗
    - 'DOMAIN-SUFFIX,idouyinvod.com'
    - 'DOMAIN-SUFFIX,idouyinstatic.com'
    - 'DOMAIN-SUFFIX,amemv.com' #手机视频流
    - 'DOMAIN-SUFFIX,snssdk.com'
    - 'DOMAIN-SUFFIX,pstatp.com'
    - 'DOMAIN-SUFFIX,ipstatp.com'
    - 'DOMAIN-SUFFIX,zjcdn.com'
    - 'DOMAIN-SUFFIX,bdurl.net'
    - 'DOMAIN-SUFFIX,umeng.com'
    - 'DOMAIN-SUFFIX,tanx.com'